eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9100/eureka/
server:
  port: 9130
spring:
  application:
    name: service-feign
ribbon:
  eureka:
    enabled: true


